#/************************************************************************************
#** File: - Makefile
#** Copyright (C), 2008-2020, OPLUS Mobile Comm Corp., Ltd
#**
#** Description:
#**      1. Add for sla
#**
#** Version: 1.0
#** Date :   2021-7-17
#** Author:  LianGenglin@CONNECTIVITY.WIFI.INTERNET
#** TAG  :   OPLUS_FEATURE_WIFI_SLA
#**
#** ---------------------Revision History: ---------------------
#**  <author>                      <data>     <version >   <desc>
#** ---------------------------------------------------------------
#**  LianGenglin@CONNECTIVITY.WIFI.INTERNET  2020/05/09  1.0          build this module
#**
#************************************************************************************/

#
# Makefile for the netfilter modules on top of IPv4.
#
obj-$(CONFIG_OPLUS_FEATURE_WIFI_SLA) += oplus_connectivity_sla.o
