#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
oplus_bsp_tp_s6sy792-y += sec_drivers_s6sy792.o
obj-$(CONFIG_TOUCHPANEL_SAMSUNG_S6SY792) += oplus_bsp_tp_s6sy792.o
#endif
