# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

#/**********************************************************************************
#** ---------------------Revision History: ---------------------
#**  <author>                      <data>     <version >   <desc>
#** ---------------------------------------------------------------
#**
#***********************************************************************************/

#
# Makefile for the network power monitor
#
obj-$(CONFIG_OPLUS_FEATURE_NWPOWER) += oplus_nwpower.o