obj-$(CONFIG_OPCHAIN) += uxcore/
obj-$(CONFIG_OPCHAIN) += uxcore/core/

obj-$(CONFIG_MEMPLUS) += memplus/
obj-$(CONFIG_MEMPLUS) += memplus/core/

obj-$(CONFIG_SMART_BOOST) += smartboost/
obj-$(CONFIG_SMART_BOOST) += smartboost/core/

obj-$(CONFIG_DEFRAG) += defrag/
obj-$(CONFIG_DEFRAG) += defrag/core/

obj-$(CONFIG_FSC) += fsc/
obj-$(CONFIG_HOUSTON) += houston/
obj-$(CONFIG_OP_FREEZER) += op_freezer/
obj-$(CONFIG_CONTROL_CENTER) += control_center/
obj-$(CONFIG_IM) += im/
obj-$(CONFIG_TPD) += tpd/
obj-$(CONFIG_PCCORE) += pccore/
obj-$(CONFIG_TPP) += tpp/
obj-$(CONFIG_VM_FRAGMENT_MONITOR) += vm_fragment_monitor/
obj-$(CONFIG_ZWB_HANDLE) += zwb_handle/
obj-$(CONFIG_UXCHAIN) += uxchain/
obj-$(CONFIG_MEMEX_STANDALONE) += memex_standalone_support/core/

obj-$(CONFIG_CPUFREQ_BOUNCING) += cpufreq_bouncing/
