#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHPANEL_ST_ST80Y) += ST80Y/

oplus_bsp_tp_st_comnon-y += st_common.o
obj-$(CONFIG_TOUCHPANEL_ST) += oplus_bsp_tp_st_comnon.o
#endif
