#/************************************************************************************
#** File: - Makefile
#** VENDOR_EDIT
#** Copyright (C), 2008-2020, OPLUS Mobile Comm Corp., Ltd
#**
#** Description:
#**      1. Add for dhcp conflict
#**
#** Version: 1.0
#** Date :   2020-05-09
#** TAG  :   OPLUS_FEATURE_DHCP_CONFLICT
#**
#** ---------------------Revision History: ---------------------
#**  <author>                      <data>     <version >   <desc>
#** ---------------------------------------------------------------
#**
#************************************************************************************/

#
# Makefile for the netfilter modules on top of IPv4.
#
obj-$(CONFIG_OPLUS_FEATURE_WIFI_DHCP) += oplus_connectivity_dhcp.o
