#/************************************************************************************
#** File: - Makefile
#** VENDOR_EDIT
#** Copyright (C), 2008-2020, Oplus Mobile Comm Corp., Ltd
#**
#** Description:
#**      1. Add for WeChat lucky money recognition
#**
#** Version: 1.0
#** Date :   2020-03-20
#** TAG  :   OPLUS_FEATURE_WIFI_LUCKYMONEY
#**
#** ---------------------Revision History: ---------------------
#**  <author>                      <data>     <version >   <desc>
#** ---------------------------------------------------------------
#**
#************************************************************************************/

#
# Makefile for the netfilter modules on top of IPv4.
#
obj-$(CONFIG_OPLUS_FEATURE_WIFI_LUCKYMONEY) += oplus_connectivity_luckymoney.o
