#ifndef _TOF_CORE1_MAINAPP_ALG_RES2_REG_H
#define _TOF_CORE1_MAINAPP_ALG_RES2_REG_H


// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!     THIS FILE HAS BEEN GENERATED AUTOMATICALLY       !!
// !!                     DO NOT EDIT                      !!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!



#define OL_RES2_NUMBER_OFFSET 0x20
#define OL_RES2_NUMBER (I2CBUS_BASE_ADDR+OL_RES2_NUMBER_OFFSET)
// 0   
#define OL_RES2_NUMBER__result_num__WIDTH 8
#define OL_RES2_NUMBER__result_num__SHIFT 0

#define OL_RES2_INFO_0_OFFSET 0x21
#define OL_RES2_INFO_0 (I2CBUS_BASE_ADDR+OL_RES2_INFO_0_OFFSET)
// 0   
#define OL_RES2_INFO_0__reliability_5_0__WIDTH 6
#define OL_RES2_INFO_0__reliability_5_0__SHIFT 0
// 0   
#define OL_RES2_INFO_0__resultStatus__WIDTH 2
#define OL_RES2_INFO_0__resultStatus__SHIFT 6

#define OL_RES2_DIST_PEAK_0_OFFSET 0x22
#define OL_RES2_DIST_PEAK_0 (I2CBUS_BASE_ADDR+OL_RES2_DIST_PEAK_0_OFFSET)
// 0   
#define OL_RES2_DIST_PEAK_0__distance_peak_7_0__WIDTH 8
#define OL_RES2_DIST_PEAK_0__distance_peak_7_0__SHIFT 0

#define OL_RES2_DIST_PEAK_1_OFFSET 0x23
#define OL_RES2_DIST_PEAK_1 (I2CBUS_BASE_ADDR+OL_RES2_DIST_PEAK_1_OFFSET)
// 0   
#define OL_RES2_DIST_PEAK_1__distance_peak_15_8__WIDTH 8
#define OL_RES2_DIST_PEAK_1__distance_peak_15_8__SHIFT 0

#define OL_RES2_SYS_CLOCK_0_OFFSET 0x24
#define OL_RES2_SYS_CLOCK_0 (I2CBUS_BASE_ADDR+OL_RES2_SYS_CLOCK_0_OFFSET)
// 0   
#define OL_RES2_SYS_CLOCK_0__sys_clock_7_0__WIDTH 8
#define OL_RES2_SYS_CLOCK_0__sys_clock_7_0__SHIFT 0

#define OL_RES2_SYS_CLOCK_1_OFFSET 0x25
#define OL_RES2_SYS_CLOCK_1 (I2CBUS_BASE_ADDR+OL_RES2_SYS_CLOCK_1_OFFSET)
// 0   
#define OL_RES2_SYS_CLOCK_1__sys_clock_15_8__WIDTH 8
#define OL_RES2_SYS_CLOCK_1__sys_clock_15_8__SHIFT 0

#define OL_RES2_SYS_CLOCK_2_OFFSET 0x26
#define OL_RES2_SYS_CLOCK_2 (I2CBUS_BASE_ADDR+OL_RES2_SYS_CLOCK_2_OFFSET)
// 0   
#define OL_RES2_SYS_CLOCK_2__sys_clock_23_16__WIDTH 8
#define OL_RES2_SYS_CLOCK_2__sys_clock_23_16__SHIFT 0

#define OL_RES2_SYS_CLOCK_3_OFFSET 0x27
#define OL_RES2_SYS_CLOCK_3 (I2CBUS_BASE_ADDR+OL_RES2_SYS_CLOCK_3_OFFSET)
// 0   
#define OL_RES2_SYS_CLOCK_3__sys_clock_31_24__WIDTH 8
#define OL_RES2_SYS_CLOCK_3__sys_clock_31_24__SHIFT 0

#define OL_RES2_STATE_DATA_0_OFFSET 0x28
#define OL_RES2_STATE_DATA_0 (I2CBUS_BASE_ADDR+OL_RES2_STATE_DATA_0_OFFSET)
// 0   
#define OL_RES2_STATE_DATA_0__state_data_0__WIDTH 8
#define OL_RES2_STATE_DATA_0__state_data_0__SHIFT 0

#define OL_RES2_STATE_DATA_1_OFFSET 0x29
#define OL_RES2_STATE_DATA_1 (I2CBUS_BASE_ADDR+OL_RES2_STATE_DATA_1_OFFSET)
// 0   
#define OL_RES2_STATE_DATA_1__state_data_1__WIDTH 8
#define OL_RES2_STATE_DATA_1__state_data_1__SHIFT 0

#define OL_RES2_STATE_DATA_2_OFFSET 0x2A
#define OL_RES2_STATE_DATA_2 (I2CBUS_BASE_ADDR+OL_RES2_STATE_DATA_2_OFFSET)
// 0   
#define OL_RES2_STATE_DATA_2__state_data_2__WIDTH 8
#define OL_RES2_STATE_DATA_2__state_data_2__SHIFT 0

#define OL_RES2_STATE_DATA_3_OFFSET 0x2B
#define OL_RES2_STATE_DATA_3 (I2CBUS_BASE_ADDR+OL_RES2_STATE_DATA_3_OFFSET)
// 0   
#define OL_RES2_STATE_DATA_3__state_data_3__WIDTH 8
#define OL_RES2_STATE_DATA_3__state_data_3__SHIFT 0

#define OL_RES2_STATE_DATA_4_OFFSET 0x2C
#define OL_RES2_STATE_DATA_4 (I2CBUS_BASE_ADDR+OL_RES2_STATE_DATA_4_OFFSET)
// 0   
#define OL_RES2_STATE_DATA_4__state_data_4__WIDTH 8
#define OL_RES2_STATE_DATA_4__state_data_4__SHIFT 0

#define OL_RES2_STATE_DATA_5_OFFSET 0x2D
#define OL_RES2_STATE_DATA_5 (I2CBUS_BASE_ADDR+OL_RES2_STATE_DATA_5_OFFSET)
// 0   
#define OL_RES2_STATE_DATA_5__state_data_5__WIDTH 8
#define OL_RES2_STATE_DATA_5__state_data_5__SHIFT 0

#define OL_RES2_STATE_DATA_6_OFFSET 0x2E
#define OL_RES2_STATE_DATA_6 (I2CBUS_BASE_ADDR+OL_RES2_STATE_DATA_6_OFFSET)
// 0   
#define OL_RES2_STATE_DATA_6__state_data_6__WIDTH 8
#define OL_RES2_STATE_DATA_6__state_data_6__SHIFT 0

#define OL_RES2_STATE_DATA_7_OFFSET 0x2F
#define OL_RES2_STATE_DATA_7 (I2CBUS_BASE_ADDR+OL_RES2_STATE_DATA_7_OFFSET)
// 0   
#define OL_RES2_STATE_DATA_7__state_data_7__WIDTH 8
#define OL_RES2_STATE_DATA_7__state_data_7__SHIFT 0

#define OL_RES2_STATE_DATA_8_OFFSET 0x30
#define OL_RES2_STATE_DATA_8 (I2CBUS_BASE_ADDR+OL_RES2_STATE_DATA_8_OFFSET)
// 0   
#define OL_RES2_STATE_DATA_8__state_data_8__WIDTH 8
#define OL_RES2_STATE_DATA_8__state_data_8__SHIFT 0

#define OL_RES2_STATE_DATA_9_OFFSET 0x31
#define OL_RES2_STATE_DATA_9 (I2CBUS_BASE_ADDR+OL_RES2_STATE_DATA_9_OFFSET)
// 0   
#define OL_RES2_STATE_DATA_9__state_data_9__WIDTH 8
#define OL_RES2_STATE_DATA_9__state_data_9__SHIFT 0

#define OL_RES2_STATE_DATA_10_OFFSET 0x32
#define OL_RES2_STATE_DATA_10 (I2CBUS_BASE_ADDR+OL_RES2_STATE_DATA_10_OFFSET)
// 0   
#define OL_RES2_STATE_DATA_10__state_data_10__WIDTH 8
#define OL_RES2_STATE_DATA_10__state_data_10__SHIFT 0

#define OL_RES2_REFERENCE_HITS_0_OFFSET 0x33
#define OL_RES2_REFERENCE_HITS_0 (I2CBUS_BASE_ADDR+OL_RES2_REFERENCE_HITS_0_OFFSET)
// 0   
#define OL_RES2_REFERENCE_HITS_0__reference_hits_7_0__WIDTH 8
#define OL_RES2_REFERENCE_HITS_0__reference_hits_7_0__SHIFT 0

#define OL_RES2_REFERENCE_HITS_1_OFFSET 0x34
#define OL_RES2_REFERENCE_HITS_1 (I2CBUS_BASE_ADDR+OL_RES2_REFERENCE_HITS_1_OFFSET)
// 0   
#define OL_RES2_REFERENCE_HITS_1__reference_hits_15_8__WIDTH 8
#define OL_RES2_REFERENCE_HITS_1__reference_hits_15_8__SHIFT 0

#define OL_RES2_REFERENCE_HITS_2_OFFSET 0x35
#define OL_RES2_REFERENCE_HITS_2 (I2CBUS_BASE_ADDR+OL_RES2_REFERENCE_HITS_2_OFFSET)
// 0   
#define OL_RES2_REFERENCE_HITS_2__reference_hits_23_16__WIDTH 8
#define OL_RES2_REFERENCE_HITS_2__reference_hits_23_16__SHIFT 0

#define OL_RES2_REFERENCE_HITS_3_OFFSET 0x36
#define OL_RES2_REFERENCE_HITS_3 (I2CBUS_BASE_ADDR+OL_RES2_REFERENCE_HITS_3_OFFSET)
// 0   
#define OL_RES2_REFERENCE_HITS_3__reference_hits_31_24__WIDTH 8
#define OL_RES2_REFERENCE_HITS_3__reference_hits_31_24__SHIFT 0

#define OL_RES2_OBJECT_HITS_0_OFFSET 0x37
#define OL_RES2_OBJECT_HITS_0 (I2CBUS_BASE_ADDR+OL_RES2_OBJECT_HITS_0_OFFSET)
// 0   
#define OL_RES2_OBJECT_HITS_0__object_hits_7_0__WIDTH 8
#define OL_RES2_OBJECT_HITS_0__object_hits_7_0__SHIFT 0

#define OL_RES2_OBJECT_HITS_1_OFFSET 0x38
#define OL_RES2_OBJECT_HITS_1 (I2CBUS_BASE_ADDR+OL_RES2_OBJECT_HITS_1_OFFSET)
// 0   
#define OL_RES2_OBJECT_HITS_1__object_hits_15_8__WIDTH 8
#define OL_RES2_OBJECT_HITS_1__object_hits_15_8__SHIFT 0

#define OL_RES2_OBJECT_HITS_2_OFFSET 0x39
#define OL_RES2_OBJECT_HITS_2 (I2CBUS_BASE_ADDR+OL_RES2_OBJECT_HITS_2_OFFSET)
// 0   
#define OL_RES2_OBJECT_HITS_2__object_hits_23_16__WIDTH 8
#define OL_RES2_OBJECT_HITS_2__object_hits_23_16__SHIFT 0

#define OL_RES2_OBJECT_HITS_3_OFFSET 0x3A
#define OL_RES2_OBJECT_HITS_3 (I2CBUS_BASE_ADDR+OL_RES2_OBJECT_HITS_3_OFFSET)
// 0   
#define OL_RES2_OBJECT_HITS_3__object_hits_31_24__WIDTH 8
#define OL_RES2_OBJECT_HITS_3__object_hits_31_24__SHIFT 0

#define OL_RES2_NUM_ADD_TARGETS_OFFSET 0x3B
#define OL_RES2_NUM_ADD_TARGETS (I2CBUS_BASE_ADDR+OL_RES2_NUM_ADD_TARGETS_OFFSET)
// 0   
#define OL_RES2_NUM_ADD_TARGETS__num_add_targets__WIDTH 8
#define OL_RES2_NUM_ADD_TARGETS__num_add_targets__SHIFT 0

#define OL_RES2_ADD_RELIABILITY_0_OFFSET 0x3C
#define OL_RES2_ADD_RELIABILITY_0 (I2CBUS_BASE_ADDR+OL_RES2_ADD_RELIABILITY_0_OFFSET)
// 0   
#define OL_RES2_ADD_RELIABILITY_0__add_reliability_7_0__WIDTH 8
#define OL_RES2_ADD_RELIABILITY_0__add_reliability_7_0__SHIFT 0

#define OL_RES2_ADD_RELIABILITY_1_OFFSET 0x3D
#define OL_RES2_ADD_RELIABILITY_1 (I2CBUS_BASE_ADDR+OL_RES2_ADD_RELIABILITY_1_OFFSET)
// 0   
#define OL_RES2_ADD_RELIABILITY_1__add_reliability_15_8__WIDTH 8
#define OL_RES2_ADD_RELIABILITY_1__add_reliability_15_8__SHIFT 0

#define OL_RES2_ADD_DIST_PEAK_0_OFFSET 0x3E
#define OL_RES2_ADD_DIST_PEAK_0 (I2CBUS_BASE_ADDR+OL_RES2_ADD_DIST_PEAK_0_OFFSET)
// 0   
#define OL_RES2_ADD_DIST_PEAK_0__add_dist_peak_7_0__WIDTH 8
#define OL_RES2_ADD_DIST_PEAK_0__add_dist_peak_7_0__SHIFT 0

#define OL_RES2_ADD_DIST_PEAK_1_OFFSET 0x3F
#define OL_RES2_ADD_DIST_PEAK_1 (I2CBUS_BASE_ADDR+OL_RES2_ADD_DIST_PEAK_1_OFFSET)
// 0   
#define OL_RES2_ADD_DIST_PEAK_1__add_dist_peak_15_8__WIDTH 8
#define OL_RES2_ADD_DIST_PEAK_1__add_dist_peak_15_8__SHIFT 0

#endif
