
#define OPLUS_CHG_IC_BUCK		0x00
#define OPLUS_CHG_IC_BOOST		0x01
#define OPLUS_CHG_IC_BUCK_BOOST		0x02
#define OPLUS_CHG_IC_CP_DIV2		0x03
#define OPLUS_CHG_IC_CP_MUL2		0x04
#define OPLUS_CHG_IC_CP_TW2		0x05
#define OPLUS_CHG_IC_RX			0x06
#define OPLUS_CHG_IC_VIRTUAL_RX		0x07
#define OPLUS_CHG_IC_VIRTUAL_BUCK	0x08
#define OPLUS_CHG_IC_VIRTUAL_CP		0x09
#define OPLUS_CHG_IC_VIRTUAL_USB	0x0a
#define OPLUS_CHG_IC_TYPEC		0x0b
