#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHPANEL_SAMSUNG_S6SY792) += S6SY792/

oplus_bsp_tp_sec_comnon-y += sec_common.o
obj-$(CONFIG_TOUCHPANEL_SAMSUNG) += oplus_bsp_tp_sec_comnon.o
#endif
