#
# Makefile for tri_state_key driver
#

tri_key-objs += \
	/hall_ic/hall_mxm1120_down.o \
	/hall_ic/hall_mxm1120_up.o \
	/ist_hall_ic/hall_ist8801_down.o \
	/ist_hall_ic/hall_ist8801_up.o \
	oneplus_tri_key.o \
	tri_key_module_init.o

obj-$(CONFIG_TRI_STATE_KEY) += tri_key.o
