ccflags-$(CONFIG_MTK_PLATFORM) += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-$(CONFIG_MTK_PLATFORM) += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/

oplus_bsp_device_info-y			:= device_info.o
obj-$(CONFIG_OPLUS_DEVICE_IFNO)	+= oplus_bsp_device_info.o
